### PR TITLE
White burger when on the header, black otherwise

### PR DESCRIPTION
**Pull request by rpunkfu**
This implements feature from #8. This is how it looks:

gif

### CODE REVIEW

**Comment by tj** [comment]
rad, thanks!

**Comment by tj** [comment]
oops, I get 45 is not a function

**Comment by rpunkfu** [comment]
Hmm, will look into that right away ;)

**Comment by oskarcieslik** [comment]
Sorry but can't find this PR merged anywhere in repo, any help?

**Comment by oskarcieslik** [comment]
Got it, nevermind ;)

**Pull request merged**
